import datetime
import pytest

import pandas as pd
import numpy as np

from google.api_core.datetime_helpers import DatetimeWithNanoseconds

from app.app import app as flask_app
from models.config_model import Config
from models.interviewer_call_pattern_model import InterviewerCallPattern, InterviewerCallPatternRefactored


@pytest.fixture
def config():
    return Config(
        mysql_host="blah",
        mysql_user="blah",
        mysql_password="blah",
        mysql_database="blah",
        blaise_api_url="blah",
        nifi_staging_bucket="blah"
    )


@pytest.fixture
def api_installed_questionnaires_response():
    return [
        {
            "name": "DST2106X",
            "id": "12345-12345-12345-12345-XXXXX",
            "serverParkName": "gusty",
            "installDate": "2021-01-01T01:01:01.99999+01:00",
            "status": "Active",
            "dataRecordCount": 1337,
            "hasData": True,
            "nodes": [
                {
                    "nodeName": "blaise-gusty-mgmt",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-1",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-2",
                    "nodeStatus": "Active"
                }
            ]
        },
        {
            "name": "DST2106Y",
            "id": "12345-12345-12345-12345-YYYYY",
            "serverParkName": "gusty",
            "installDate": "2021-01-01T01:01:01.99999+01:00",
            "status": "Active",
            "dataRecordCount": 42,
            "hasData": True,
            "nodes": [
                {
                    "nodeName": "blaise-gusty-mgmt",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-1",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-2",
                    "nodeStatus": "Active"
                }
            ]
        },
        {
            "name": "DST2106Z",
            "id": "12345-12345-12345-12345-ZZZZZ",
            "serverParkName": "gusty",
            "installDate": "2021-01-01T01:01:01.99999+01:00",
            "status": "Active",
            "dataRecordCount": 999,
            "hasData": True,
            "nodes": [
                {
                    "nodeName": "blaise-gusty-mgmt",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-1",
                    "nodeStatus": "Active"
                },
                {
                    "nodeName": "blaise-gusty-data-entry-2",
                    "nodeStatus": "Active"
                }
            ]
        }
    ]


@pytest.fixture
def questionnaire_name():
    return "DST2106Z"


@pytest.fixture
def questionnaire_fields_to_get():
    return [
        "QID.Serial_Number",
        "QHAdmin.HOut"
    ]


@pytest.fixture
def api_reporting_data_response():
    return {
        "instrumentName": "DST2106Z",
        "instrumentId": "12345-12345-12345-12345-12345",
        "reportingData": [
            {
                "qiD.Serial_Number": "10010",
                "qhAdmin.HOut": "110"
            },
            {
                "qiD.Serial_Number": "10020",
                "qhAdmin.HOut": "110"
            },
            {
                "qiD.Serial_Number": "10030",
                "qhAdmin.HOut": "110"

            }
        ]
    }


@pytest.fixture
def interviewer_name():
    return "ricer"


@pytest.fixture
def start_date_string():
    return "2021-01-01"


@pytest.fixture
def end_date_string():
    return "2022-01-01"


@pytest.fixture
def invalid_date():
    return "blah"


@pytest.fixture
def app():
    yield flask_app


@pytest.fixture
def client(app):
    return app.test_client()


@pytest.fixture
def valid_dataframe():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 4, 22, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 36, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 204,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 31, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 4, 42, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 49,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 580,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 43, 32, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 45, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 107,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 28, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 43, 59, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 29,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 46, 12, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 52, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 80,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 48, 2, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 46, 36, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 86,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 49, 43, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 48, 21, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 82,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 5, 48, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 5, 1, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 47,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 51, 49, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 51, 3, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 46,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 52, 47, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 52, 7, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 40,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        }
    ]
    return pd.DataFrame(results)


@pytest.fixture
def dataframe_with_some_invalid_fields():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': np.nan,
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 36, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 204,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 31, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 4, 42, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 49,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 580,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 43, 32, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 45, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 107,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 28, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 43, 59, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 29,
            'interviewer': 'el4president',
            'number_of_interviews': np.nan,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 46, 12, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 52, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 80,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 48, 2, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 46, 36, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 86,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 49, 43, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 48, 21, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 82,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 5, 48, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': np.nan,
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 47,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 51, 49, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 51, 3, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 46,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 52, 47, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 52, 7, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 40,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        }
    ]
    return pd.DataFrame(results)


@pytest.fixture
def call_history_with_all_invalid_records():
    return [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': np.nan,
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 36, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 204,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 31, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 4, 42, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 49,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 580,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Timed out',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 28, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': "",
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 29,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]


@pytest.fixture
def dataframe_with_all_invalid_fields():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': np.nan,
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 36, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 204,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 31, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 4, 42, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 49,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 580,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Timed out',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 43, 32, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 41, 45, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 107,
            'interviewer': 'el4president',
            'number_of_interviews': np.nan,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 44, 28, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': "",
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 29,
            'interviewer': 'el4president',
            'number_of_interviews': np.nan,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)


@pytest.fixture
def dodgy_date_value_dataframe():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': 'SURPRISE!!!!',
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 53, 3, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 30,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 54, 21, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 53, 49, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 32,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 55, 6, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 54, 33, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 33,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)


@pytest.fixture
def unexpected_time_totals_dataframe():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 53, 5, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 53, 3, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 300,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-928350fdda5a',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 54, 21, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 53, 49, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 3200,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 460,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 55, 6, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 54, 33, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 3300,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)


@pytest.fixture
def missing_dataframe():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': None,
            'call_number': 2,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 55, 27, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 210,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 15, 1, 1, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 14, 59, 33, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 97,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 15, 1, 42, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 15, 1, 34, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 8,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        }
    ]
    return pd.DataFrame(results)


@pytest.fixture
def status_dataframe():
    results = [
        {
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 4, 34, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 85,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 7, 53, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 6, 19, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 94,
            'interviewer': 'el4president',
            'number_of_interviews': 2,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 1, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 9, 24, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 60,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 11, 44, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 1, 31, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 73,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 14, 56, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 14, 1, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 55,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Others',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Others',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Others',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Questionnaire',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (Appointment made)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 47, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 2, 45, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 23, 31, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 57, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 94,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 23, 31, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 57, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 94,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 23, 31, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 21, 57, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 94,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 28, 51, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 25, 36, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 195,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 48, 29, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 37, 52, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 637,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 5, 51, tzinfo=datetime.timezone.utc),
            'call_number': 3,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 9, 15, 56, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 2995,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Completed',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 45, 18, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 44, 26, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 52,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 56, 35, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 55, 39, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 56,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 58, 18, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 1, 57, 15, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 63,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
    ]

    return pd.DataFrame(results)


@pytest.fixture
def call_history_dataframe_with_timed_out_questionnaire():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 2, 15, 35, 21, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Appointment',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 2, 15, 5, 5, tzinfo=datetime.timezone.utc),
            'cohort': 'CC',
            'dial_number': 1,
            'dial_secs': 1816,
            'interviewer': 'el4president',
            'number_of_interviews': 1,
            'outcome_code': 300,
            'questionnaire_id': 'remember-24-01-57f4c0f090be',
            'questionnaire_name': 'LMS2107_CC1',
            'serial_number': 24012022,
            'status': 'Timed out during questionnaire',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)


@pytest.fixture
def call_history_records():
    return [
        {
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 4, 34, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 8,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 7, 53, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 6, 19, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 9,
            'interviewer': 'el4president',
            'number_of_interviews': "2",
            'outcome_code': 110,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 1, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 9, 24, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 6,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 14, 56, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 14, 1, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 5,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Questionnaire',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 5,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (Non response)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 5,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 16, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 16, 25, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 51,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 18, 24, tzinfo=datetime.timezone.utc),
            'call_number': 2,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 8, 17, 22, tzinfo=datetime.timezone.utc),
            'cohort': None,
            'dial_number': 1,
            'dial_secs': 62,
            'interviewer': 'el4president',
            'number_of_interviews': "1",
            'outcome_code': 310,
            'questionnaire_id': 'remember-24-01-9dc791f0cb07',
            'questionnaire_name': 'OPN2108R',
            'serial_number': 24012022,
            'status': 'Finished (No contact)',
            'survey': 'OPN',
            'update_info': None,
            'wave': None
        },
    ]


@pytest.fixture
def interviewer_call_pattern_report():
    return InterviewerCallPattern(
        hours_worked="7:24:00",
        call_time="0:00:00",
        hours_on_calls_percentage="0%",
        average_calls_per_hour=3.14,
        respondents_interviewed=5,
        average_respondents_interviewed_per_hour=123,
        refusals="foobar",
        no_contacts="foobar",
        no_contact_answer_service="foobar",
        no_contact_busy="foobar",
        no_contact_disconnect="foobar",
        no_contact_no_answer="foobar",
        no_contact_other="foobar",
        completed_successfully="",
        appointments_for_contacts="100/100, 100%",
        discounted_invalid_cases="0",
        invalid_fields="n/a",
    )

@pytest.fixture()
def hours_worked_greater_than_24_hours():
    results = [{
        'appointment_info': None,
        'busy_dials': 0,
        'call_end_time': DatetimeWithNanoseconds(2021, 8, 8, 00, 50, 00, tzinfo=datetime.timezone.utc),
        'call_number': 1,
        'call_result': 'NoAnswer',
        'call_start_time': DatetimeWithNanoseconds(2021, 8, 7, 00, 00, 00, tzinfo=datetime.timezone.utc),
        'cohort': None,
        'dial_number': 1,
        'dial_secs': 89400,
        'interviewer': 'el4president',
        'number_of_interviews': "1",
        'outcome_code': 310,
        'questionnaire_id': 'remember-24-01-9dc791f0cb07',
        'questionnaire_name': 'OPN2108R',
        'serial_number': 24012022,
        'status': 'Finished (No contact)',
        'survey': 'OPN',
        'update_info': None,
        'wave': None
    }]
    return pd.DataFrame(results)