import datetime
import pytest
import pandas as pd
from app.app import app as flask_app
from google.api_core.datetime_helpers import DatetimeWithNanoseconds


@pytest.fixture
def app():
    yield flask_app


@pytest.fixture
def client(app):
    return app.test_client()


@pytest.fixture
def mock_data():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 12, 33, 21, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 12, 32, 16, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 65,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-1a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 32, 43, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 32, 22, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 21,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-2a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 33, 40, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 33, 11, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 29,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 35, 34, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 35, 29, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 5,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 36, 8, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 36, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 8,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-4a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 49, 55, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 49, 40, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 4,
            'dial_secs': 15,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-4a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': "You've been Numberwanged!",
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 59, 17, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 59, 1, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 16,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-4a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (Successful)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 13, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 7, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 5,
            'dial_secs': 6,
            'interviewer': 'matpal',
            'number_of_interviews': 1,
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-5a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)


@pytest.fixture
def uber_mock_data():
    results = [
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 59, 17, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 59, 1, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 16,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 2, 27, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 2, 22, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 5,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 3, 52, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 3, 34, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 18,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 12, 46, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 12, 38, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 8,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 13, 40, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 13, 28, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 4,
            'dial_secs': 12,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': None,
            'call_number': 1,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 15, 11, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 5,
            'dial_secs': None,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '460',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001011',
            'status': 'Questionnaire',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': None,
            'call_number': 1,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 11, 49, 33, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': None,
            'interviewer': 'nik',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Questionnaire',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 32, 43, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 32, 22, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 21,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 33, 40, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 33, 11, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 29,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 35, 34, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 35, 29, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 5,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 36, 8, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 36, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 8,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 49, 55, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 14, 49, 40, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 4,
            'dial_secs': 15,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 13, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 7, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 5,
            'dial_secs': 6,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 55, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 0, 49, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 6,
            'dial_secs': 6,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '561',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001021',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 20, 15, 30, 9, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 20, 15, 29, 50, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 19,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '390',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001031',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 8, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 7, 45, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 15,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '390',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001031',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 11, 59, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 11, 52, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 7,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '390',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001031',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 1,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 13, 3, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Disconnect',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 12, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 5,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '390',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001031',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 13, 41, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 20, 16, 13, 25, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 16,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '390',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001031',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': None,
            'call_number': 1,
            'call_result': None,
            'call_start_time': DatetimeWithNanoseconds(2021, 6, 14, 13, 21, 23, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': None,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '310',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001061',
            'status': 'Questionnaire',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 12, 33, 21, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 12, 32, 16, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 1,
            'dial_secs': 65,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 19, 26, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'AnswerService',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 19, 15, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 2,
            'dial_secs': 11,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 23, 29, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NoAnswer',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 23, 22, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 3,
            'dial_secs': 7,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 24, 26, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'NonRespons',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 23, 49, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 4,
            'dial_secs': 37,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (Non response)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
        {
            'appointment_info': None,
            'busy_dials': 0,
            'call_end_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 25, 5, tzinfo=datetime.timezone.utc),
            'call_number': 1,
            'call_result': 'Busy',
            'call_start_time': DatetimeWithNanoseconds(2021, 5, 19, 15, 24, 58, tzinfo=datetime.timezone.utc),
            'cohort': 'AA',
            'dial_number': 5,
            'dial_secs': 7,
            'interviewer': 'matpal',
            'number_of_interviews': '1',
            'outcome_code': '542',
            'questionnaire_id': '05cf69af-3a4e-47df-819a-928350fdda5a',
            'questionnaire_name': 'LMS2101_AA1',
            'serial_number': '1001081',
            'status': 'Finished (No contact)',
            'survey': 'LMS',
            'update_info': None,
            'wave': 1
        },
    ]
    return pd.DataFrame(results)



