from models.mi_hub_respondent_data_model import MiHubRespondentData


def test_mi_hub_respondent_data():
    mi_hub_respondent_data = MiHubRespondentData(
        serial_number="",
        outcome_code="",
        date_completed="",
        interviewer="",
        mode="",
        postcode="",
        gender="",
        date_of_birth="",
        age="",
        Case_ID="",
        ShiftNo="",
        Interv="",
        CaseNotes="",
        Flight1="",
        Flight2="",
        Flight3="",
        Flight4="",
        Flight5="",
        Flight6="",
        Flight7="",
        Flight8="",
        IntDate="",
        SelectionTime="",
        DMExitTime="",
        IntType="",
        SampInterval="",
        ShiftType="",
        Portroute="",
        Baseport="",
        Linecode="",
        FlightNum="",
        DVFlightNum="",
        PortCode="",
        PortDestination="",
        Shuttle="",
        CrossShut="",
        Vehicle="",
        IsElig="",
        FerryTime="",
        Flow="",
        DVRespnse="",
        proportion="",
        response_visitbritain="",
        response_age_sex="",
        response_student="",
        response_fe_trailer="",
        response_migration_trailer="",
        DMTimeIsElig="",
        DMTimeAgeSex="",
        UKForeign="",
        StudyCheck="",
        Expenditure="",
        Age="",
        Sex=""
    )
    assert mi_hub_respondent_data is not None
